# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.4
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: true
odoo_version: 13.0
rebel_module_groups: []
repo_description: Odoo modules related to Manufacturing
repo_name: Odoo Manufacturing Modules
repo_slug: manufacture
travis_apt_packages: []
travis_apt_sources: []
